
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 30 2018 19:00:53 GMT+0200 (Central Europe Daylight Time).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class Event extends ContentItem {
    public picturesFromPreviousYears: Fields.AssetsField;
    public openingDaysInAYearFrom: Fields.TextField;
    public description: Fields.RichTextField;
    public poiGroupPointsOfInterest: ContentItem[];
    public urlSlug: Fields.UrlSlugField;
    public poiGroupTitle: Fields.TextField;
    public openingDaysInAYearUntil: Fields.TextField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'pictures_from_previous_years') {
                    return 'picturesFromPreviousYears';
                }
                if (fieldName === 'opening_days__in_a_year___from') {
                    return 'openingDaysInAYearFrom';
                }
                if (fieldName === 'poi_group__points_of_interest') {
                    return 'poiGroupPointsOfInterest';
                }
                if (fieldName === 'url_slug') {
                    return 'urlSlug';
                }
                if (fieldName === 'poi_group__title') {
                    return 'poiGroupTitle';
                }
                if (fieldName === 'opening_days__in_a_year___until') {
                    return 'openingDaysInAYearUntil';
                }
                return fieldName;
            })
        });
    }
}
