
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 30 2018 19:00:53 GMT+0200 (Central Europe Daylight Time).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class PointOfInterest extends ContentItem {
    public urlSlug: Fields.UrlSlugField;
    public pictures: Fields.AssetsField;
    public description: Fields.RichTextField;
    public latitudeDecimalDegrees: Fields.NumberField;
    public avatar: Fields.AssetsField;
    public longitudeDecimalDegrees: Fields.NumberField;
    public relatedPointsOfInterest: ContentItem[];
    public title: Fields.TextField;
    public elevationFt: Fields.NumberField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'url_slug') {
                    return 'urlSlug';
                }
                if (fieldName === 'latitude__decimal_degrees_') {
                    return 'latitudeDecimalDegrees';
                }
                if (fieldName === 'longitude__decimal_degrees_') {
                    return 'longitudeDecimalDegrees';
                }
                if (fieldName === 'related_points_of_interest') {
                    return 'relatedPointsOfInterest';
                }
                if (fieldName === 'elevation__ft_') {
                    return 'elevationFt';
                }
                return fieldName;
            })
        });
    }
}
