
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 30 2018 19:00:53 GMT+0200 (Central Europe Daylight Time).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class Tour extends ContentItem {
    public images: Fields.AssetsField;
    public poiGroupPointsOfInterest: ContentItem[];
    public description: Fields.RichTextField;
    public poiGroupTitle: Fields.TextField;
    public tourType: Fields.MultipleChoiceField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'poi_group__points_of_interest') {
                    return 'poiGroupPointsOfInterest';
                }
                if (fieldName === 'poi_group__title') {
                    return 'poiGroupTitle';
                }
                if (fieldName === 'tour_type') {
                    return 'tourType';
                }
                return fieldName;
            })
        });
    }
}
