sudo: required
dist: trusty
language: node_js
node_js:
- "stable"
addons:
  google-chrome-beta
before_install:
- google-chrome-beta --headless --no-sandbox
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: kentico-cloud-sample-angular-pwa-app.surge.sh 
  skip_cleanup: true
