sudo: required
dist: trusty
language: node_js
node_js:
- "stable"
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: kentico-cloud-sample-angular-pwa-app.surge.sh 
  skip_cleanup: true
