sudo: required
dist: trusty
language: node_js
node_js:
- lts/*
before_script:
- npm install
script:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: https://kentico-cloud-sample-angular-pwa-app.surge.sh 
  skip_cleanup: true
after_deploy:
- npm run check-pwa-score